### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by Krystex**
Hello @kaichaosun! Thank you for your awesome project.

I mostly use Docker at home, so I built a docker container for your project. Today or tomorrow I will add instructions how to run it.

### CODE REVIEW

**Comment by Krystex** [comment]
@kaichaosun, what would you think of extending the CLI with an option to bind the server at a custom ip? By default, your app binds on 127.0.0.1, but for the docker container it would be better to bind on all interfaces (0.0.0.0).

**Comment by kaichaosun** [comment]
Hey @Krystex, the ip can be set with CLI parameter, check [here](https://github.com/kaichaosun/rlt/blob/main/cli/src/main.rs#L29), or do I misunderstood your idea with extending the CLI?

Change the default binding to `0.0.0.0` sounds great!

**Comment by Krystex** [comment]
Sorry I should clarify, I'm talking about the server, not the client. It seems like the binding to 127.0.0.1 is hardcoded, see [here](https://github.com/kaichaosun/rlt/blob/34a471b33985aa615852f7502fc76579b21c06c8/server/src/lib.rs#L65) and [here](https://github.com/kaichaosun/rlt/blob/34a471b33985aa615852f7502fc76579b21c06c8/server/src/lib.rs#L99)

**Comment by kaichaosun** [comment]
Ah, I see. Extend the server CLI parameter seems not necessary to me, since only `0.0.0.0` or `127.0.0.1` will be used here.

**Comment by kaichaosun** [comment]
thanks for your contribution!

**Pull request merged**
